"""
全局配置文件
"""

from dataclasses import dataclass
from typing import Optional
import os


@dataclass
class CrawlerConfig:
    """爬虫配置类"""
    
    # 语言配置
    language: str = "zh"  # 默认简体中文，可选: "zh" | "en"
    
    # 输出配置
    output_dir: str = "output"  # 可自定义输出目录
    save_raw_html: bool = False  # 是否保存原始HTML
    save_content: bool = True    # 是否保存提取的内容
    
    # 分类文件夹配置
    create_category_folders: bool = True  # 是否按分类创建文件夹
    
    # Markdown索引配置
    generate_markdown_index: bool = True  # 是否生成Markdown索引
    
    # 爬取配置
    max_pages: int = 50
    pages_per_query: int = 5
    https_proxy: Optional[str] = None  # 可选代理，例如 http://127.0.0.1:7890
    
    @property
    def content_dir(self) -> str:
        """内容保存目录"""
        return os.path.join(self.output_dir, "content")
    
    @property
    def index_dir(self) -> str:
        """索引文件目录"""
        return os.path.join(self.output_dir, "index")
    
    def get_category_dir(self, domain: str, category: str) -> str:
        """获取分类目录路径"""
        # 清理文件夹名称
        safe_domain = self._sanitize_folder_name(domain)
        safe_category = self._sanitize_folder_name(category)
        return os.path.join(self.content_dir, safe_domain, safe_category)
    
    def _sanitize_folder_name(self, name: str) -> str:
        """清理文件夹名称，移除非法字符"""
        import re
        # 替换非法字符
        safe = re.sub(r'[<>:"/\\|?*]', '_', name)
        # 限制长度
        return safe[:100]
    
    def get_text(self, key: str) -> str:
        """获取对应语言的文本"""
        return TRANSLATIONS.get(self.language, TRANSLATIONS["zh"]).get(key, key)


# 多语言翻译
TRANSLATIONS = {
    "zh": {
        # 通用
        "title": "标题",
        "content": "内容",
        "url": "链接",
        "summary": "摘要",
        "category": "分类",
        "categories": "分类列表",
        "page_count": "页面数量",
        "total_pages": "总页面数",
        "domain": "领域",
        "analysis": "分析",
        "key_concepts": "关键概念",
        "main_topics": "主要主题",
        "relevance_score": "相关度",
        "index_summary": "索引摘要",
        
        # 分类相关
        "auto_generated_categories": "自动生成的分类",
        "category_relations": "分类关系",
        "uncategorized_pages": "未分类页面",
        
        # 文件相关
        "index_file": "索引文件",
        "saved_to": "保存至",
        "created_at": "创建时间",
        
        # 页面信息
        "word_count": "字数",
        "char_count": "字符数",
        "technical_level": "技术难度",
        
        # Markdown标题
        "md_title_template": "{domain} - Wikipedia 内容索引",
        "md_overview": "📊 概述",
        "md_category_prefix": "📁 分类",
        "md_page_list": "📄 页面列表",
        "md_uncategorized": "📝 未分类页面",
        "md_category_relations": "🔗 分类关系",
        "md_footer": "由 Oxygent Wikipedia Crawler 自动生成",
    },
    "en": {
        # General
        "title": "Title",
        "content": "Content",
        "url": "URL",
        "summary": "Summary",
        "category": "Category",
        "categories": "Categories",
        "page_count": "Page Count",
        "total_pages": "Total Pages",
        "domain": "Domain",
        "analysis": "Analysis",
        "key_concepts": "Key Concepts",
        "main_topics": "Main Topics",
        "relevance_score": "Relevance Score",
        "index_summary": "Index Summary",
        
        # Category related
        "auto_generated_categories": "Auto-generated Categories",
        "category_relations": "Category Relations",
        "uncategorized_pages": "Uncategorized Pages",
        
        # File related
        "index_file": "Index File",
        "saved_to": "Saved to",
        "created_at": "Created At",
        
        # Page info
        "word_count": "Word Count",
        "char_count": "Char Count",
        "technical_level": "Technical Level",
        
        # Markdown headers
        "md_title_template": "{domain} - Wikipedia Content Index",
        "md_overview": "📊 Overview",
        "md_category_prefix": "📁 Category",
        "md_page_list": "📄 Page List",
        "md_uncategorized": "📝 Uncategorized Pages",
        "md_category_relations": "🔗 Category Relations",
        "md_footer": "Generated by Oxygent Wikipedia Crawler",
    }
}


# 全局配置实例
_config: Optional[CrawlerConfig] = None


def get_config() -> CrawlerConfig:
    """获取全局配置"""
    global _config
    if _config is None:
        _config = CrawlerConfig()
    return _config


def set_config(config: CrawlerConfig):
    """设置全局配置"""
    global _config
    _config = config


def init_config(
    output_dir: str = "output",
    language: str = "zh",
    max_pages: int = 50,
    **kwargs
) -> CrawlerConfig:
    """
    初始化全局配置
    
    Args:
        output_dir: 输出目录路径
        language: 语言代码 ("zh" 或 "en")
        max_pages: 最大爬取页面数
        **kwargs: 其他配置参数
    
    Returns:
        CrawlerConfig实例
    """
    global _config
    _config = CrawlerConfig(
        output_dir=output_dir,
        language=language,
        max_pages=max_pages,
        **kwargs
    )
    return _config
