"""
wikipediagent
使用Oxygent构建的Wikipedia内容自动爬取与智能分类系统

功能：
1. Plan Agent制定爬取计划
2. 爬取指定数量的领域相关页面
3. 并行SubAgent分析页面内容
4. Clustering Agent自动归纳分类
5. 保存到本地分类文件夹
6. 生成Markdown索引文件（支持中英文）

使用方法：
1. 复制 .env.example 为 .env 并填写API密钥
2. 运行: python main.py
"""

import asyncio
import json
import os
import re
from typing import List, Dict, Any
from datetime import datetime

from dotenv import load_dotenv
from oxygent import MAS, oxy, Config

import prompts
import tools
from config import get_config, CrawlerConfig, set_config, init_config

# 加载环境变量
load_dotenv()

# 设置Oxygent配置
Config.set_agent_llm_model("default_llm")
Config.set_llm_config({
    "temperature": 0.2,
    "max_tokens": 2048,
})


# ============================================
# Oxygent Space 定义 - 自动分类版本
# ============================================

def create_oxy_space(language: str = "zh"):
    """创建Oxygent Space，支持语言配置"""
    
    return [
        # ===== LLM 配置 =====
        oxy.HttpLLM(
            name="default_llm",
            api_key=os.getenv("DEFAULT_LLM_API_KEY", ""),
            base_url=os.getenv("DEFAULT_LLM_BASE_URL", "https://api.openai.com/v1"),
            model_name=os.getenv("DEFAULT_LLM_MODEL_NAME", "gpt-4o-mini"),
            llm_params={"temperature": 0.2, "max_tokens": 2048},
            semaphore=15,
            timeout=240,
        ),
        
        # ===== 工具注册 =====
        tools.wikipedia_tools,
        tools.file_tools,
        
        # ===== SubAgent 1: 规划Agent =====
        oxy.ChatAgent(
            name="plan_agent",
            desc="A planning expert that creates Wikipedia crawling strategies based on domain",
            prompt=prompts.PLAN_AGENT_PROMPT,
            llm_model="default_llm",
        ),
        
        # ===== SubAgent 2: 页面分析Agent（将被并行调用） =====
        oxy.ChatAgent(
            name="page_analyzer",
            desc="An expert that analyzes Wikipedia page content and extracts topics/concepts",
            prompt=prompts.ANALYSIS_AGENT_PROMPT,
            llm_model="default_llm",
            semaphore=10,
        ),
        
        # ===== SubAgent 3: 聚类分类Agent（自动生成分类） =====
        oxy.ChatAgent(
            name="clustering_agent",
            desc="An expert that automatically clusters and categorizes analyzed content into groups",
            prompt=prompts.CLUSTERING_AGENT_PROMPT,
            llm_model="default_llm",
        ),
        
        # ===== Master Agent =====
        oxy.ReActAgent(
            name="master_agent",
            desc=f"""Master agent that orchestrates Wikipedia crawling with automatic categorization.
            
            Workflow:
            1. Call plan_agent to create crawling plan (domain + max_pages)
            2. Use crawl_wikipedia_pages to fetch pages based on plan
            3. Parallel call page_analyzer for each page to extract topics/concepts
            4. Call clustering_agent to automatically generate categories from analyzed content
            5. Use save_categorized_content to save results to local folders and generate Markdown index
            
            Key Points:
            - Categories are AUTO-GENERATED by clustering_agent, NOT predefined
            - Results are saved to output/content/{{domain}}/{{category}}/{{title}}.md
            - Markdown index is generated at output/index/{{domain}}_index.md
            - Output language: {language} (zh=简体中文, en=English)
            """,
            is_master=True,
            sub_agents=["plan_agent", "page_analyzer", "clustering_agent"],
            tools=["wikipedia_tools", "file_tools"],
            llm_model="default_llm",
            semaphore=15,
            timeout=600,
        ),
    ]


# ============================================
# 辅助函数
# ============================================

def create_crawl_request(
    domain: str,
    max_pages: int = 50,
    language: str = "zh"
) -> str:
    """
    创建爬取请求（自动分类 + 本地保存版本）
    
    Args:
        domain: 领域名称
        max_pages: 最大爬取页面数
        language: 输出语言，"zh"=简体中文，"en"=英文
    
    Returns:
        格式化的查询字符串
    """
    lang_text = "简体中文" if language == "zh" else "English"
    
    return f"""请帮我爬取Wikipedia上关于"{domain}"领域的内容，自动分类并保存到本地。

任务配置：
- 目标领域：{domain}
- 爬取页面数：{max_pages}个
- 输出语言：{lang_text}
- 分类方式：AI自动归纳分类

执行步骤：

1. 【制定计划】调用 plan_agent 制定爬取计划：
   - domain: "{domain}"
   - max_pages: {max_pages}
   - language: "{language}"
   
2. 【爬取页面】使用 crawl_wikipedia_pages 爬取页面：
   - queries: 使用plan_agent返回的search_queries
   - max_pages: {max_pages}
   - pages_per_query: 合理设置以覆盖不同方向

3. 【并行分析】对每个爬取到的页面，**并行**调用 page_analyzer 进行分析：
   输入参数：
   - page_title: "页面标题"
   - page_content: "页面内容（前3000字符）"
   - target_domain: "{domain}"
   - language: "{language}"
   
   收集每个页面的：main_topics, key_concepts, suggested_category_tags, analysis_summary

4. 【自动聚类】所有页面分析完成后，调用 clustering_agent 自动归纳分类：
   - 传入所有页面的分析结果
   - 参数 language: "{language}"（重要：确保输出使用指定语言）
   - clustering_agent会根据内容自动生成合理的分类体系
   - 每个分类包含：category_name（{lang_text}）, description（{lang_text}）, pages

5. 【保存结果】使用 save_categorized_content 保存到本地：
   - domain: "{domain}"
   - categorized_data: clustering_agent的完整输出
   - language: "{language}"
   
   此工具会自动：
   - 创建文件夹结构：output/content/{domain}/{{category}}/
   - 保存每个页面为Markdown文件
   - 生成Markdown索引：output/index/{domain}_index.md
   - 保存JSON数据：output/{domain}_data.json

重要提醒：
- **不要预设分类**，让clustering_agent基于内容自动归纳
- 确保并行调用page_analyzer以提高效率
- 所有描述性文字使用{lang_text}
- 页面标题和内容保留英文，摘要和分类使用{lang_text}

请开始执行！"""


def _extract_mas_text(result: Any) -> str:
    """兼容不同 OxyGent 版本的返回字段。"""
    if hasattr(result, "output") and isinstance(result.output, str):
        return result.output
    if hasattr(result, "answer") and isinstance(result.answer, str):
        return result.answer
    return str(result)


def _is_timeout_response(text: str) -> bool:
    """判断MAS返回文本是否为超时/取消类失败。"""
    lower = (text or "").lower()
    return (
        "timed out" in lower
        or "timeout" in lower
        or "was cancelled" in lower
        or "tool default_llm timed out" in lower
    )


def _extract_json_object(text: str) -> Dict[str, Any]:
    """Try to extract a JSON object from raw LLM text responses."""
    if not text:
        return {}

    candidate = text.strip()

    # Remove markdown code fence if present.
    if candidate.startswith("```"):
        candidate = re.sub(r"^```(?:json)?\\s*", "", candidate, flags=re.IGNORECASE)
        candidate = re.sub(r"\\s*```$", "", candidate)

    # Fast path: exact JSON object.
    try:
        parsed = json.loads(candidate)
        return parsed if isinstance(parsed, dict) else {}
    except Exception:
        pass

    # Fallback: first {...} block.
    start = candidate.find("{")
    end = candidate.rfind("}")
    if start >= 0 and end > start:
        snippet = candidate[start:end + 1]
        try:
            parsed = json.loads(snippet)
            return parsed if isinstance(parsed, dict) else {}
        except Exception:
            return {}

    return {}


async def _run_query_with_retry(mas: MAS, query: str, retries: int = 1) -> tuple[Any, float, bool]:
    """执行MAS查询，遇到超时文本时进行有限重试。"""
    start_time = datetime.now()
    result: Any = ""
    timed_out = False

    for attempt in range(retries + 1):
        result = await mas.chat_with_agent(payload={"query": query})
        result_text = _extract_mas_text(result)
        timed_out = _is_timeout_response(result_text)
        if not timed_out:
            break
        if attempt < retries:
            print(f"\n⚠️ 检测到LLM超时，正在重试 ({attempt + 1}/{retries})...")

    elapsed = (datetime.now() - start_time).total_seconds()
    return result, elapsed, timed_out


# ============================================
# 主程序
# ============================================

async def main(output_dir: str = "output", language: str = "zh"):
    """
    主入口函数 - 自动分类 + 本地保存版本
    
    Args:
        output_dir: 输出目录路径，默认为 "output"
        language: 输出语言，默认为 "zh" (简体中文)
    """
    
    # 初始化配置
    config = init_config(
        output_dir=output_dir,
        language=language,
        max_pages=50
    )
    
    # 配置列表
    crawl_configs = [
        {
            "domain": "Computer Science",
            "max_pages": 50,
            "language": "zh"  # 简体中文
        },
        # 可以添加更多领域或语言...
        # {
        #     "domain": "Artificial Intelligence",
        #     "max_pages": 30,
        #     "language": "en"  # 英文
        # },
    ]
    
    # 确保输出目录存在
    os.makedirs(config.content_dir, exist_ok=True)
    os.makedirs(config.index_dir, exist_ok=True)
    
    print("=" * 70)
    print("🚀 Oxygent Wikipedia Crawler - 自动分类与本地保存")
    print("=" * 70)
    print("\n📋 特性：")
    print("   • Plan-Execute 工作流")
    print("   • 并行页面分析")
    print("   • AI自动归纳分类")
    print("   • 分类文件夹保存")
    print("   • Markdown索引生成（支持中英文）")
    print("=" * 70)
    
    for crawl_config in crawl_configs:
        domain = crawl_config["domain"]
        max_pages = crawl_config["max_pages"]
        language = crawl_config.get("language", "zh")
        
        # 更新全局配置
        config.language = language
        
        # 创建Oxygent Space
        oxy_space = create_oxy_space(language)
        
        print(f"\n📚 开始爬取领域: {domain}")
        print(f"   目标页面数: {max_pages}")
        print(f"   输出语言: {'简体中文' if language == 'zh' else 'English'}")
        print(f"   分类方式: AI自动归纳")
        print("-" * 70)
        
        # 创建爬取请求
        query = create_crawl_request(domain, max_pages, language)
        
        try:
            async with MAS(oxy_space=oxy_space) as mas:
                # 执行爬取任务
                result, elapsed, timed_out = await _run_query_with_retry(mas, query, retries=1)
                summary_text = _extract_mas_text(result)

                if timed_out:
                    print(f"\n❌ 爬取失败: {domain}")
                    print(f"   原因: LLM 调用超时（已重试）")
                    print(f"   耗时: {elapsed:.1f}秒")
                    summary = summary_text[:1000] if len(summary_text) > 1000 else summary_text
                    print(f"\n📋 错误摘要:\n{summary}")
                    continue

                print(f"\n✅ 爬取完成: {domain}")
                print(f"   耗时: {elapsed:.1f}秒")
                print(f"\n📁 输出文件：")
                print(f"   • 分类文件夹: {config.output_dir}/content/{domain.replace(' ', '_')}/")
                print(f"   • Markdown索引: {config.output_dir}/index/{domain.replace(' ', '_')}_index.md")
                print(f"   • JSON数据: {config.output_dir}/{domain.replace(' ', '_')}_data.json")

                summary = summary_text[:1000] if len(summary_text) > 1000 else summary_text
                print(f"\n📋 结果摘要:\n{summary}")
                
        except Exception as e:
            print(f"\n❌ 爬取失败: {domain}")
            print(f"   错误: {str(e)}")
            import traceback
            traceback.print_exc()
    
    print("\n" + "=" * 70)
    print("✨ 所有爬取任务已完成！")
    print("=" * 70)


async def quick_demo(output_dir: str = "output"):
    """
    快速演示模式 - 简化版自动分类
    
    Args:
        output_dir: 输出目录路径
    """
    # 初始化配置
    config = init_config(
        output_dir=output_dir,
        language="zh",
        max_pages=10
    )
    
    print("=" * 70)
    print("🚀 Oxygent Wikipedia Crawler - Quick Demo")
    print("=" * 70)
    
    # 简化版oxy_space
    demo_space = [
        oxy.HttpLLM(
            name="default_llm",
            api_key=os.getenv("DEFAULT_LLM_API_KEY", ""),
            base_url=os.getenv("DEFAULT_LLM_BASE_URL", "https://api.openai.com/v1"),
            model_name=os.getenv("DEFAULT_LLM_MODEL_NAME", "gpt-4o-mini"),
            llm_params={"temperature": 0.2, "max_tokens": 2048},
            semaphore=10,
            timeout=240,
        ),
        tools.wikipedia_tools,
        tools.file_tools,
        oxy.ReActAgent(
            name="master_agent",
            desc="""Wikipedia crawling master agent with automatic categorization.
            
            Workflow:
            1. Plan search queries for the domain
            2. Crawl pages using crawl_wikipedia_pages
            3. Analyze content and extract topics
            4. Auto-categorize based on content similarity
            5. Save to local folders and generate Markdown index using save_categorized_content
            
            Categories are determined automatically based on page content analysis.
            Output language: Chinese (简体中文)
            """,
            is_master=True,
            tools=["wikipedia_tools", "file_tools"],
            llm_model="default_llm",
            semaphore=10,
            timeout=300,
        ),
    ]
    
    # 确保输出目录存在
    os.makedirs(config.content_dir, exist_ok=True)
    os.makedirs(config.index_dir, exist_ok=True)
    
    async with MAS(oxy_space=demo_space) as mas:
        query = """Crawl Wikipedia pages about "Data Structures and Algorithms" in Computer Science.

Requirements:
1. Crawl 8 pages total
2. Search queries: Array, Linked List, Tree, Sorting Algorithm, Graph Algorithm
3. For each page, analyze its main topics and key concepts
4. **Automatically group** pages into natural categories based on content
5. Save results using save_categorized_content:
   - domain: "Computer Science"
   - language: "zh" (简体中文)
   - Create folder structure: output/content/Computer Science/{category}/
   - Generate Markdown index: output/index/Computer Science_index.md

Output should be in Chinese (简体中文)."""
        
        print("\n📚 开始爬取: Data Structures and Algorithms")
        print("   目标页面数: 8")
        print("   输出语言: 简体中文")
        print("-" * 70)
        
        try:
            result, elapsed, timed_out = await _run_query_with_retry(mas, query, retries=1)
            result_text = _extract_mas_text(result)

            if timed_out:
                print(f"\n❌ 爬取失败！耗时: {elapsed:.1f}秒")
                print("   原因: LLM 调用超时（已重试）")
                print(f"\n📋 错误摘要:\n{result_text[:800]}")
                return

            print(f"\n✅ 爬取完成！耗时: {elapsed:.1f}秒")
            print(f"\n📁 输出文件：")
            print(f"   • 分类文件夹: {config.output_dir}/content/Computer Science/")
            print(f"   • Markdown索引: {config.output_dir}/index/Computer Science_index.md")
            print(f"   • JSON数据: {config.output_dir}/Computer Science_data.json")

            print(f"\n📋 结果:\n{result_text}")
        except Exception as e:
            print(f"\n❌ 错误: {str(e)}")
            import traceback
            traceback.print_exc()
    
    print("\n" + "=" * 70)
    print("✨ Demo 完成！")
    print("=" * 70)


async def custom_crawl(
    domain: str, 
    max_pages: int, 
    language: str = "zh",
    output_dir: str = "output",
    hard_parallel: bool = False,
    parallel_workers: int = 10,
):
    """
    自定义爬取函数
    
    Args:
        domain: 领域名称
        max_pages: 最大页面数
        language: 语言，"zh"或"en"
        output_dir: 输出目录路径
    """
    # 初始化配置
    config = init_config(
        output_dir=output_dir,
        language=language,
        max_pages=max_pages
    )
    
    # 创建Oxygent Space
    oxy_space = create_oxy_space(language)
    
    print("=" * 70)
    print(f"🚀 自定义爬取: {domain}")
    print("=" * 70)
    print(f"   目标页面数: {max_pages}")
    print(f"   输出语言: {'简体中文' if language == 'zh' else 'English'}")
    if hard_parallel:
        print(f"   分析模式: 代码硬并发 ({parallel_workers}并发/批次)")
    else:
        print("   分析模式: Agent 自主调度 (可能串行)")
    
    # 确保输出目录存在
    os.makedirs(config.content_dir, exist_ok=True)
    os.makedirs(config.index_dir, exist_ok=True)
    
    # 创建请求
    query = create_crawl_request(domain, max_pages, language)

    try:
        async with MAS(oxy_space=oxy_space) as mas:
            if not hard_parallel:
                result, elapsed, timed_out = await _run_query_with_retry(mas, query, retries=1)
                result_text = _extract_mas_text(result)

                if timed_out:
                    print(f"\n❌ 爬取失败！耗时: {elapsed:.1f}秒")
                    print("   原因: LLM 调用超时（已重试）")
                    print(f"\n📋 错误摘要:\n{result_text[:800]}")
                    return

                print(f"\n✅ 爬取完成！耗时: {elapsed:.1f}秒")
                print(f"\n📁 输出文件：")
                print(f"   • 分类文件夹: {config.output_dir}/content/{domain.replace(' ', '_')}/")
                print(f"   • Markdown索引: {config.output_dir}/index/{domain.replace(' ', '_')}_index.md")

                print(f"\n📋 结果摘要:\n{result_text[:800]}")
                return

            # ===== Hard parallel path: deterministic 10-way (or configured) batch analysis =====
            started_at = datetime.now()

            print("\n🧠 Step 1/4: 生成搜索计划...")
            plan_query = f'''Create a Wikipedia crawl plan in JSON only.
Input:
- domain: "{domain}"
- max_pages: {max_pages}
- language: "{language}"

Required JSON fields:
- search_queries: string[]
- search_strategy: string
- estimated_pages: number
- expected_subtopics: string[]

Return JSON only.'''
            plan_result = await mas.chat_with_agent(payload={"query": plan_query})
            plan_data = _extract_json_object(_extract_mas_text(plan_result))
            search_queries = plan_data.get("search_queries", []) if isinstance(plan_data, dict) else []
            if not isinstance(search_queries, list):
                search_queries = []
            search_queries = [str(q).strip() for q in search_queries if str(q).strip()]
            if not search_queries:
                search_queries = [f"{domain} overview", domain]

            print(f"   计划关键词数: {len(search_queries)}")

            print("\n📥 Step 2/4: 爬取页面...")
            crawl_text = await tools.crawl_wikipedia_pages(
                queries=search_queries,
                max_pages=max_pages,
                pages_per_query=max(2, min(5, parallel_workers // 2)),
            )
            crawl_data = _extract_json_object(crawl_text)
            pages = crawl_data.get("pages", []) if isinstance(crawl_data, dict) else []
            if not isinstance(pages, list):
                pages = []
            if not pages:
                print("\n❌ 爬取失败：未获取到任何页面")
                return

            print(f"   实际爬取页面数: {len(pages)}")

            print(f"\n⚡ Step 3/4: 并行分析页面（每批 {parallel_workers} 并发）...")
            analyzed_pages: List[Dict[str, Any]] = []

            # Ensure valid worker count.
            workers = max(1, int(parallel_workers))

            for start in range(0, len(pages), workers):
                batch = pages[start:start + workers]
                analysis_requests = []
                for page in batch:
                    title = str(page.get("title", ""))
                    content = str(page.get("content", ""))[:3000]
                    req = f'''Analyze this page and return JSON only.
Input:
- page_title: "{title}"
- page_content: """{content}"""
- target_domain: "{domain}"
- language: "{language}"

Required JSON fields:
- is_relevant
- relevance_score
- analysis_summary
- main_topics
- key_concepts
- technical_level
- suggested_category_tags
- related_areas'''
                    analysis_requests.append(req)

                print(f"   批次 {start // workers + 1}: 提交 {len(analysis_requests)} 个并发分析请求")
                batch_results = await mas.start_batch_processing(
                    analysis_requests,
                    return_trace_id=True,
                )

                for idx, (_, answer) in enumerate(batch_results):
                    page = batch[idx] if idx < len(batch) else {}
                    analysis = _extract_json_object(str(answer))
                    analyzed_pages.append({
                        "title": page.get("title", "Untitled"),
                        "url": page.get("url", ""),
                        "content": page.get("content", ""),
                        "analysis": analysis,
                    })

            print(f"   分析完成页面数: {len(analyzed_pages)}")

            print("\n🗂️ Step 4/4: 自动聚类并保存...")
            clustering_input = []
            for item in analyzed_pages:
                analysis = item.get("analysis", {}) if isinstance(item.get("analysis"), dict) else {}
                clustering_input.append({
                    "title": item.get("title", ""),
                    "url": item.get("url", ""),
                    "content": item.get("content", ""),
                    "main_topics": analysis.get("main_topics", []),
                    "key_concepts": analysis.get("key_concepts", []),
                    "suggested_category_tags": analysis.get("suggested_category_tags", []),
                    "analysis_summary": analysis.get("analysis_summary", ""),
                    "relevance_score": analysis.get("relevance_score", 0),
                })

            clustering_query = f'''Cluster analyzed Wikipedia pages and return JSON only.
Input:
- target_domain: "{domain}"
- total_pages: {len(clustering_input)}
- language: "{language}"
- analyzed_pages: {json.dumps(clustering_input, ensure_ascii=False)[:12000]}

Output JSON fields:
- domain
- total_pages
- auto_generated_categories
- category_relations
- uncategorized_pages
- index_summary'''

            cluster_result = await mas.chat_with_agent(payload={"query": clustering_query})
            categorized_data = _extract_json_object(_extract_mas_text(cluster_result))
            if not categorized_data:
                categorized_data = {
                    "domain": domain,
                    "total_pages": len(clustering_input),
                    "auto_generated_categories": [
                        {
                            "category_name": "Uncategorized",
                            "description": "Fallback category generated by system.",
                            "page_count": len(clustering_input),
                            "pages": [
                                {
                                    "title": p.get("title", "Untitled"),
                                    "url": p.get("url", ""),
                                    "content": p.get("content", ""),
                                    "summary": p.get("analysis_summary", ""),
                                    "key_concepts": p.get("key_concepts", []),
                                    "relevance_score": p.get("relevance_score", 0),
                                }
                                for p in clustering_input
                            ],
                        }
                    ],
                    "category_relations": [],
                    "uncategorized_pages": [],
                    "index_summary": "Generated by fallback path due to non-JSON cluster response.",
                }

            save_result = tools.save_categorized_content(
                domain=domain,
                categorized_data=categorized_data,
                language=language,
            )

            elapsed = (datetime.now() - started_at).total_seconds()
            print(f"\n✅ 爬取完成！耗时: {elapsed:.1f}秒")
            print(f"\n📁 输出文件：")
            print(f"   • 分类文件夹: {config.output_dir}/content/{domain.replace(' ', '_')}/")
            print(f"   • Markdown索引: {config.output_dir}/index/{domain.replace(' ', '_')}_index.md")
            print(f"\n📋 保存结果:\n{save_result[:800]}")

    except Exception as e:
        print(f"\n❌ 错误: {str(e)}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    import sys
    import argparse
    
    # 创建命令行参数解析器
    parser = argparse.ArgumentParser(
        description="Oxygent Wikipedia Crawler - 自动分类与本地保存",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
使用示例:
  python main.py                                    # 标准模式，输出到 output/
  python main.py --output ./my_data                 # 指定输出目录
  python main.py --demo                             # 快速演示
  python main.py --demo --output ./demo_output      # 演示模式 + 指定输出目录
  python main.py --custom "Physics" 30              # 自定义领域和数量
  python main.py --custom "Physics" 30 --output ./physics_data --lang en
        """
    )
    
    parser.add_argument(
        "--output", "-o",
        type=str,
        default="output",
        help="输出目录路径 (默认: output)"
    )
    
    parser.add_argument(
        "--demo",
        action="store_true",
        help="运行快速演示模式"
    )
    
    parser.add_argument(
        "--custom",
        type=str,
        metavar="DOMAIN",
        help="自定义爬取领域，如 'Computer Science'"
    )
    
    parser.add_argument(
        "--pages", "-p",
        type=int,
        default=30,
        help="爬取页面数量 (默认: 30，用于 --custom 模式)"
    )
    
    parser.add_argument(
        "--lang", "-l",
        type=str,
        choices=["zh", "en"],
        default="zh",
        help="输出语言: zh=简体中文, en=英文 (默认: zh)"
    )

    parser.add_argument(
        "--hard-parallel",
        action="store_true",
        help="在 --custom 模式启用代码层并发分析（避免Agent串行调度）"
    )

    parser.add_argument(
        "--parallel-workers",
        type=int,
        default=10,
        help="--hard-parallel 模式每批并发分析数 (默认: 10)"
    )

    # 兼容旧用法: --custom "Physics" 30 zh
    parser.add_argument(
        "legacy_pages",
        nargs="?",
        type=int,
        help=argparse.SUPPRESS
    )

    parser.add_argument(
        "legacy_lang",
        nargs="?",
        choices=["zh", "en"],
        help=argparse.SUPPRESS
    )
    
    args = parser.parse_args()
    
    # 根据参数执行相应模式
    if args.demo:
        # 快速演示模式
        asyncio.run(quick_demo(output_dir=args.output))
    elif args.custom:
        # 自定义爬取模式
        pages = args.legacy_pages if args.legacy_pages is not None else args.pages
        language = args.legacy_lang if args.legacy_lang is not None else args.lang

        asyncio.run(custom_crawl(
            domain=args.custom,
            max_pages=pages,
            language=language,
            output_dir=args.output,
            hard_parallel=args.hard_parallel,
            parallel_workers=args.parallel_workers,
        ))
    else:
        # 标准模式
        asyncio.run(main(output_dir=args.output, language=args.lang))
