"""
并行分析 + 自动聚类分类
"""

import asyncio
import json
import os
from typing import List, Dict, Any

from dotenv import load_dotenv
from oxygent import MAS, oxy, Config

import prompts
import tools

load_dotenv()

Config.set_agent_llm_model("default_llm")
Config.set_llm_config({
    "temperature": 0.2,
    "max_tokens": 2048,
})


def _extract_mas_text(result: Any) -> str:
    """兼容不同 OxyGent 版本的返回字段。"""
    if hasattr(result, "output") and isinstance(result.output, str):
        return result.output
    if hasattr(result, "answer") and isinstance(result.answer, str):
        return result.answer
    return str(result)


# ============================================
# 使用ParallelAgent的oxy_space定义
# ============================================

oxy_space_parallel = [
    # LLM
    oxy.HttpLLM(
        name="default_llm",
        api_key=os.getenv("DEFAULT_LLM_API_KEY", ""),
        base_url=os.getenv("DEFAULT_LLM_BASE_URL", "https://api.openai.com/v1"),
        model_name=os.getenv("DEFAULT_LLM_MODEL_NAME", "gpt-4o-mini"),
        llm_params={"temperature": 0.2, "max_tokens": 2048},
        semaphore=25,
        timeout=120,
    ),
    
    # 工具
    tools.wikipedia_tools,
    tools.file_tools,
    
    # Plan Agent
    oxy.ChatAgent(
        name="plan_agent",
        desc="Creates Wikipedia crawling plan based on domain",
        prompt=prompts.PLAN_AGENT_PROMPT,
        llm_model="default_llm",
    ),
    
    # 多个Page Analyzer实例（用于并行分析）
    oxy.ChatAgent(
        name="analyzer_1",
        desc="Analyzes Wikipedia page content and extracts topics",
        prompt=prompts.ANALYSIS_AGENT_PROMPT,
        llm_model="default_llm",
    ),
    oxy.ChatAgent(
        name="analyzer_2",
        desc="Analyzes Wikipedia page content and extracts topics",
        prompt=prompts.ANALYSIS_AGENT_PROMPT,
        llm_model="default_llm",
    ),
    oxy.ChatAgent(
        name="analyzer_3",
        desc="Analyzes Wikipedia page content and extracts topics",
        prompt=prompts.ANALYSIS_AGENT_PROMPT,
        llm_model="default_llm",
    ),
    oxy.ChatAgent(
        name="analyzer_4",
        desc="Analyzes Wikipedia page content and extracts topics",
        prompt=prompts.ANALYSIS_AGENT_PROMPT,
        llm_model="default_llm",
    ),
    oxy.ChatAgent(
        name="analyzer_5",
        desc="Analyzes Wikipedia page content and extracts topics",
        prompt=prompts.ANALYSIS_AGENT_PROMPT,
        llm_model="default_llm",
    ),
    
    # Parallel Agent - 管理多个analyzer并行工作
    oxy.ParallelAgent(
        name="parallel_analyzer",
        desc="""Parallel page analyzer that distributes pages to multiple analyzer agents.
        Input: List of pages with their content
        Output: Combined analysis results with topics, concepts, and suggested tags for each page
        Each analyzer extracts: main_topics, key_concepts, suggested_category_tags
        """,
        permitted_tool_name_list=["analyzer_1", "analyzer_2", "analyzer_3", "analyzer_4", "analyzer_5"],
    ),
    
    # Clustering Agent - 自动聚类分类
    oxy.ChatAgent(
        name="clustering_agent",
        desc="Automatically clusters analyzed content into natural categories",
        prompt=prompts.CLUSTERING_AGENT_PROMPT,
        llm_model="default_llm",
    ),
    
    # Master Agent
    oxy.ReActAgent(
        name="master_agent",
        desc="""Master agent orchestrating Wikipedia crawling with parallel analysis and auto-categorization.
        
        Workflow:
        1. Call plan_agent to create crawling plan (domain + max_pages only)
        2. Use crawl_wikipedia_pages to fetch pages
        3. Call parallel_analyzer to analyze ALL pages in parallel (extract topics/concepts)
        4. Call clustering_agent to AUTO-GENERATE categories from analyzed content
        5. Save results
        
        KEY: NO predefined categories! Categories are generated by clustering_agent based on content.
        """,
        is_master=True,
        sub_agents=["plan_agent", "parallel_analyzer", "clustering_agent"],
        tools=["wikipedia_tools", "file_tools"],
        llm_model="default_llm",
        semaphore=15,
        timeout=600,
    ),
]


# ============================================
# 批处理模式 - 使用start_batch_processing
# ============================================

async def batch_analysis_mode():
    """
    使用批处理模式进行并行分析 + 自动分类
    """
    
    batch_space = [
        oxy.HttpLLM(
            name="default_llm",
            api_key=os.getenv("DEFAULT_LLM_API_KEY", ""),
            base_url=os.getenv("DEFAULT_LLM_BASE_URL", "https://api.openai.com/v1"),
            model_name=os.getenv("DEFAULT_LLM_MODEL_NAME", "gpt-4o-mini"),
            llm_params={"temperature": 0.2, "max_tokens": 1024},
            semaphore=25,
        ),
        tools.wikipedia_tools,
        tools.file_tools,
        oxy.ReActAgent(
            name="page_analyzer",
            desc="Analyzes Wikipedia page content and extracts topics/concepts",
            prompt=prompts.ANALYSIS_AGENT_PROMPT,
            llm_model="default_llm",
            semaphore=15,
        ),
        oxy.ReActAgent(
            name="clustering_agent",
            desc="Automatically clusters pages into categories",
            prompt=prompts.CLUSTERING_AGENT_PROMPT,
            llm_model="default_llm",
        ),
        oxy.ReActAgent(
            name="master_agent",
            is_master=True,
            sub_agents=["page_analyzer", "clustering_agent"],
            tools=["wikipedia_tools", "file_tools"],
            llm_model="default_llm",
            semaphore=15,
        ),
    ]
    
    print("=" * 70)
    print("🚀 Parallel Batch Analysis + Auto-Categorization Mode")
    print("=" * 70)
    
    os.makedirs("output", exist_ok=True)
    
    async with MAS(oxy_space=batch_space) as mas:
        # Step 1: 爬取页面
        print("\n📥 Step 1: Crawling Wikipedia pages...")
        crawl_query = """Crawl Wikipedia pages about Computer Science.

Search for these topics (max 2 pages each):
- Data Structures: Array, Linked List, Tree
- Algorithms: Sorting, Graph Algorithm, Dynamic Programming
- Systems: Operating System, Database, Network

Use crawl_wikipedia_pages with:
- queries: ["Array data structure", "Linked list", "Tree data structure", "Sorting algorithm", "Graph algorithm", "Dynamic programming", "Operating system", "Database", "Computer network"]
- max_pages: 15
- pages_per_query: 2

Return the complete results with all page contents."""
        
        crawl_result = await mas.chat_with_agent(payload={"query": crawl_query})
        print(f"✅ Crawl complete")
        
        # Step 2: 准备批量分析请求
        print("\n🔍 Step 2: Preparing batch analysis...")
        
        # 示例页面列表 - 实际应从crawl_result解析
        pages_to_analyze = [
            {"title": "Array data structure", "domain": "Computer Science"},
            {"title": "Linked list", "domain": "Computer Science"},
            {"title": "Tree (data structure)", "domain": "Computer Science"},
            {"title": "Sorting algorithm", "domain": "Computer Science"},
            {"title": "Graph theory", "domain": "Computer Science"},
            {"title": "Dynamic programming", "domain": "Computer Science"},
            {"title": "Operating system", "domain": "Computer Science"},
            {"title": "Database", "domain": "Computer Science"},
            {"title": "Computer network", "domain": "Computer Science"},
            {"title": "Hash table", "domain": "Computer Science"},
        ]
        
        analysis_requests = []
        for page in pages_to_analyze:
            req = f"""Analyze this Wikipedia page:
- Title: {page['title']}
- Target Domain: {page['domain']}

First use get_page_content to fetch the page content, then analyze and extract:
- main_topics (3-5 topics)
- key_concepts (5 key concepts)
- suggested_category_tags (3-5 tags for categorization)
- analysis_summary (100-200 words)

Return results in JSON format."""
            analysis_requests.append(req)
        
        # Step 3: 并行批处理分析
        print(f"\n⚡ Step 3: Running parallel batch analysis ({len(analysis_requests)} pages)...")
        
        batch_results = await mas.start_batch_processing(
            analysis_requests,
            return_trace_id=True
        )
        
        print(f"✅ Batch analysis complete! {len(batch_results)} pages analyzed")
        
        # Step 4: 自动聚类分类
        print("\n🗂️ Step 4: Auto-clustering into categories...")
        
        # 构建聚类请求
        analyzed_pages_data = []
        for i, (trace_id, answer) in enumerate(batch_results):
            analyzed_pages_data.append({
                "title": pages_to_analyze[i]["title"],
                "analysis_result": answer
            })
        
        cluster_query = f"""Based on the following analyzed Wikipedia pages about Computer Science,
automatically cluster them into natural categories.

Total pages: {len(analyzed_pages_data)}

Analyzed pages data:
{json.dumps(analyzed_pages_data, indent=2)[:8000]}

Task:
1. Analyze the main_topics and suggested_category_tags from each page
2. Identify natural groupings/clusters (e.g., "Data Structures", "Algorithms", "Systems")
3. Assign each page to the most appropriate category
4. Generate category descriptions

Call clustering_agent with the analyzed data to produce final categorized index.
Then save to output/batch_auto_clustered.json"""
        
        cluster_result = await mas.chat_with_agent(payload={"query": cluster_query})
        print(f"✅ Clustering complete!")
        
        # 保存结果
        print("\n💾 Step 5: Saving results...")
        output = {
            "mode": "batch_parallel_auto_cluster",
            "total_pages": len(batch_results),
            "analysis_results": [
                {"page": pages_to_analyze[i]["title"], "trace_id": r[0], "result": r[1][:500]}
                for i, r in enumerate(batch_results)
            ],
            "clustering_result": _extract_mas_text(cluster_result)
        }
        
        with open("output/batch_auto_clustered.json", "w", encoding="utf-8") as f:
            json.dump(output, f, ensure_ascii=False, indent=2)
        
        print("✅ Results saved to output/batch_auto_clustered.json")
    
    print("\n" + "=" * 70)
    print("✨ Batch analysis with auto-categorization complete!")
    print("=" * 70)


# ============================================
# 使用ParallelAgent的高级工作流
# ============================================

async def parallel_agent_workflow():
    """
    使用ParallelAgent的高级工作流 - 自动分类版本
    """
    print("=" * 70)
    print("🚀 Parallel Agent Workflow - Auto Categorization")
    print("=" * 70)
    
    os.makedirs("output", exist_ok=True)
    
    async with MAS(oxy_space=oxy_space_parallel) as mas:
        query = """Execute Wikipedia crawling workflow for "Computer Science" domain with AUTO-CATEGORIZATION.

Configuration:
- Domain: Computer Science
- Max Pages: 20
- Categorization: AUTO-GENERATED (no predefined categories)

Execution Steps:

1. Call plan_agent to create a plan:
   - domain: "Computer Science"
   - max_pages: 20

2. Use crawl_wikipedia_pages to get pages:
   - queries: based on plan
   - max_pages: 20
   - pages_per_query: 4

3. Call parallel_analyzer to analyze ALL pages in parallel:
   - Each page: extract main_topics, key_concepts, suggested_category_tags
   - Use all 5 analyzers for maximum parallelism

4. Call clustering_agent to AUTO-GENERATE categories:
   - Input: all page analysis results
   - Output: auto_generated_categories based on content similarity
   - Categories should emerge naturally from the content

5. Save to output/cs_auto_clustered_index.json

IMPORTANT: Categories are NOT predefined. Let clustering_agent analyze content and create appropriate categories!

Execute now!"""
        
        print("\n📚 Starting parallel workflow with auto-categorization...")
        print("-" * 70)
        
        try:
            result = await mas.chat_with_agent(payload={"query": query})
            print("\n✅ Workflow complete!")
            result_text = _extract_mas_text(result)
            if result_text:
                print(f"\n📋 Result summary:\n{result_text[:800]}...")
        except Exception as e:
            print(f"\n❌ Error: {str(e)}")
            import traceback
            traceback.print_exc()
    
    print("\n" + "=" * 70)
    print("✨ Parallel workflow with auto-categorization finished!")
    print("=" * 70)


if __name__ == "__main__":
    import sys
    
    mode = sys.argv[1] if len(sys.argv) > 1 else "parallel"
    
    if mode == "batch":
        asyncio.run(batch_analysis_mode())
    else:
        asyncio.run(parallel_agent_workflow())
